# Generated by Django 5.1.5 on 2026-02-21 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HairSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('wash', 'Wash Day'), ('deep_condition', 'Deep Conditioning'), ('protein_treatment', 'Protein Treatment'), ('trim', 'Trim/Haircut'), ('oil_treatment', 'Oil Treatment'), ('scalp_massage', 'Scalp Massage'), ('protective_style', 'Protective Styling'), ('clarifying_wash', 'Clarifying Wash'), ('other', 'Other')], max_length=50)),
                ('custom_event_name', models.CharField(blank=True, help_text="If event type is 'other'", max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('every_2_days', 'Every 2 Days'), ('every_3_days', 'Every 3 Days'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=20)),
                ('specific_day', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='For weekly schedules', max_length=20)),
                ('custom_interval_days', models.IntegerField(blank=True, help_text='For custom frequency', null=True)),
                ('time_of_day', models.TimeField(help_text='Preferred time for this event')),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_hours_before', models.IntegerField(default=2, help_text='Hours before event to send reminder')),
                ('reminder_email', models.EmailField(blank=True, help_text='Email for reminders', max_length=254)),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('next_scheduled', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['next_scheduled', 'time_of_day'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(auto_now_add=True)),
                ('completed_time', models.TimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, choices=[('great', '😊 Great'), ('good', '🙂 Good'), ('okay', '😐 Okay'), ('bad', '😕 Not Good')], max_length=20)),
                ('hair_condition', models.IntegerField(blank=True, help_text='Rate 1-5', null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scheduler.hairschedule')),
            ],
            options={
                'ordering': ['-completed_date', '-completed_time'],
            },
        ),
    ]
