# Generated by Django 5.1.5 on 2026-02-22 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylistApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Your salon/business name', max_length=100)),
                ('owner_name', models.CharField(help_text='Your full name', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(help_text='City/Area (e.g., Nairobi CBD, Westlands)', max_length=100)),
                ('address', models.TextField(help_text='Full physical address')),
                ('services_offered', models.TextField(help_text='List all services you offer (e.g., Braids, Weaves, Locs, etc.)')),
                ('price_range', models.CharField(help_text='e.g., KSh 1000-5000', max_length=50)),
                ('years_experience', models.IntegerField(help_text='Years in business')),
                ('portfolio_url', models.URLField(blank=True, help_text='Link to your Instagram, Facebook, or website')),
                ('sample_work_url', models.URLField(blank=True, help_text='Link to photos of your work')),
                ('business_description', models.TextField(help_text='Tell us about your business and what makes you special')),
                ('business_hours', models.CharField(help_text='e.g., Mon-Sat 9AM-6PM', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for review')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='booking.hairdresser')),
            ],
            options={
                'verbose_name': 'Stylist Application',
                'verbose_name_plural': 'Stylist Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
