# Generated by Django 5.1.5 on 2026-02-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=100)),
                ('before_photo_url', models.URLField(help_text='URL to before photo')),
                ('after_photo_url', models.URLField(help_text='URL to after photo')),
                ('hair_type', models.CharField(choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily')], max_length=20)),
                ('concern_addressed', models.CharField(choices=[('frizz', 'Frizz'), ('breakage', 'Breakage'), ('dryness', 'Dryness'), ('growth', 'Hair Growth'), ('volume', 'Volume'), ('damage', 'Damage Repair'), ('scalp', 'Scalp Health'), ('color', 'Color Treatment')], max_length=20)),
                ('time_period', models.CharField(choices=[('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('1_year_plus', '1+ Years')], max_length=20)),
                ('title', models.CharField(help_text="e.g., 'From Damaged to Healthy!'", max_length=200)),
                ('story', models.TextField(help_text='Tell your hair journey story')),
                ('routine_description', models.TextField(help_text='What routine/products did you use?')),
                ('likes', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products_used', models.ManyToManyField(blank=True, related_name='transformations', to='shop.product')),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransformationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.transformation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
